// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

package core.messages;

public final class EmploySearcher {
  private EmploySearcher() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ContractOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string dispatch_address = 1;
    /**
     * <code>required string dispatch_address = 1;</code>
     *
     * <pre>
     *The IPv4 address where the Dispatcher can be found.
     *e.g., 127.0.0.1, localhost, etc.
     * </pre>
     */
    boolean hasDispatchAddress();
    /**
     * <code>required string dispatch_address = 1;</code>
     *
     * <pre>
     *The IPv4 address where the Dispatcher can be found.
     *e.g., 127.0.0.1, localhost, etc.
     * </pre>
     */
    java.lang.String getDispatchAddress();
    /**
     * <code>required string dispatch_address = 1;</code>
     *
     * <pre>
     *The IPv4 address where the Dispatcher can be found.
     *e.g., 127.0.0.1, localhost, etc.
     * </pre>
     */
    com.google.protobuf.ByteString
        getDispatchAddressBytes();

    // required int32 experiment_port = 2;
    /**
     * <code>required int32 experiment_port = 2;</code>
     *
     * <pre>
     *The port that the dispatcher will be listening to.
     * </pre>
     */
    boolean hasExperimentPort();
    /**
     * <code>required int32 experiment_port = 2;</code>
     *
     * <pre>
     *The port that the dispatcher will be listening to.
     * </pre>
     */
    int getExperimentPort();

    // optional int32 reply_port = 3;
    /**
     * <code>optional int32 reply_port = 3;</code>
     *
     * <pre>
     *The secret to share in the communications (should be unique per contract)
     * </pre>
     */
    boolean hasReplyPort();
    /**
     * <code>optional int32 reply_port = 3;</code>
     *
     * <pre>
     *The secret to share in the communications (should be unique per contract)
     * </pre>
     */
    int getReplyPort();
  }
  /**
   * Protobuf type {@code search.Contract}
   *
   * <pre>
   *This message comes with the startup of a new core.party.Searcher to
   *let that object know where the dispatcher is, and any other
   *pertinent details needed to get the experimentation architecture
   *up and running.
   * </pre>
   */
  public static final class Contract extends
      com.google.protobuf.GeneratedMessage
      implements ContractOrBuilder {
    // Use Contract.newBuilder() to construct.
    private Contract(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Contract(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Contract defaultInstance;
    public static Contract getDefaultInstance() {
      return defaultInstance;
    }

    public Contract getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Contract(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              dispatchAddress_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              experimentPort_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              replyPort_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.messages.EmploySearcher.internal_static_search_Contract_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.messages.EmploySearcher.internal_static_search_Contract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.messages.EmploySearcher.Contract.class, core.messages.EmploySearcher.Contract.Builder.class);
    }

    public static com.google.protobuf.Parser<Contract> PARSER =
        new com.google.protobuf.AbstractParser<Contract>() {
      public Contract parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Contract(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Contract> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string dispatch_address = 1;
    public static final int DISPATCH_ADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object dispatchAddress_;
    /**
     * <code>required string dispatch_address = 1;</code>
     *
     * <pre>
     *The IPv4 address where the Dispatcher can be found.
     *e.g., 127.0.0.1, localhost, etc.
     * </pre>
     */
    public boolean hasDispatchAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string dispatch_address = 1;</code>
     *
     * <pre>
     *The IPv4 address where the Dispatcher can be found.
     *e.g., 127.0.0.1, localhost, etc.
     * </pre>
     */
    public java.lang.String getDispatchAddress() {
      java.lang.Object ref = dispatchAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dispatchAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dispatch_address = 1;</code>
     *
     * <pre>
     *The IPv4 address where the Dispatcher can be found.
     *e.g., 127.0.0.1, localhost, etc.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDispatchAddressBytes() {
      java.lang.Object ref = dispatchAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dispatchAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 experiment_port = 2;
    public static final int EXPERIMENT_PORT_FIELD_NUMBER = 2;
    private int experimentPort_;
    /**
     * <code>required int32 experiment_port = 2;</code>
     *
     * <pre>
     *The port that the dispatcher will be listening to.
     * </pre>
     */
    public boolean hasExperimentPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 experiment_port = 2;</code>
     *
     * <pre>
     *The port that the dispatcher will be listening to.
     * </pre>
     */
    public int getExperimentPort() {
      return experimentPort_;
    }

    // optional int32 reply_port = 3;
    public static final int REPLY_PORT_FIELD_NUMBER = 3;
    private int replyPort_;
    /**
     * <code>optional int32 reply_port = 3;</code>
     *
     * <pre>
     *The secret to share in the communications (should be unique per contract)
     * </pre>
     */
    public boolean hasReplyPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 reply_port = 3;</code>
     *
     * <pre>
     *The secret to share in the communications (should be unique per contract)
     * </pre>
     */
    public int getReplyPort() {
      return replyPort_;
    }

    private void initFields() {
      dispatchAddress_ = "";
      experimentPort_ = 0;
      replyPort_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDispatchAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExperimentPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDispatchAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, experimentPort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, replyPort_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDispatchAddressBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, experimentPort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, replyPort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static core.messages.EmploySearcher.Contract parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.EmploySearcher.Contract parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Contract parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.EmploySearcher.Contract parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Contract parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.EmploySearcher.Contract parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Contract parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static core.messages.EmploySearcher.Contract parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Contract parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.EmploySearcher.Contract parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(core.messages.EmploySearcher.Contract prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code search.Contract}
     *
     * <pre>
     *This message comes with the startup of a new core.party.Searcher to
     *let that object know where the dispatcher is, and any other
     *pertinent details needed to get the experimentation architecture
     *up and running.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements core.messages.EmploySearcher.ContractOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.messages.EmploySearcher.internal_static_search_Contract_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.messages.EmploySearcher.internal_static_search_Contract_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.messages.EmploySearcher.Contract.class, core.messages.EmploySearcher.Contract.Builder.class);
      }

      // Construct using core.messages.EmploySearcher.Contract.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dispatchAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        experimentPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        replyPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.messages.EmploySearcher.internal_static_search_Contract_descriptor;
      }

      public core.messages.EmploySearcher.Contract getDefaultInstanceForType() {
        return core.messages.EmploySearcher.Contract.getDefaultInstance();
      }

      public core.messages.EmploySearcher.Contract build() {
        core.messages.EmploySearcher.Contract result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public core.messages.EmploySearcher.Contract buildPartial() {
        core.messages.EmploySearcher.Contract result = new core.messages.EmploySearcher.Contract(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dispatchAddress_ = dispatchAddress_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.experimentPort_ = experimentPort_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.replyPort_ = replyPort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.messages.EmploySearcher.Contract) {
          return mergeFrom((core.messages.EmploySearcher.Contract)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.messages.EmploySearcher.Contract other) {
        if (other == core.messages.EmploySearcher.Contract.getDefaultInstance()) return this;
        if (other.hasDispatchAddress()) {
          bitField0_ |= 0x00000001;
          dispatchAddress_ = other.dispatchAddress_;
          onChanged();
        }
        if (other.hasExperimentPort()) {
          setExperimentPort(other.getExperimentPort());
        }
        if (other.hasReplyPort()) {
          setReplyPort(other.getReplyPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDispatchAddress()) {
          
          return false;
        }
        if (!hasExperimentPort()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        core.messages.EmploySearcher.Contract parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (core.messages.EmploySearcher.Contract) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string dispatch_address = 1;
      private java.lang.Object dispatchAddress_ = "";
      /**
       * <code>required string dispatch_address = 1;</code>
       *
       * <pre>
       *The IPv4 address where the Dispatcher can be found.
       *e.g., 127.0.0.1, localhost, etc.
       * </pre>
       */
      public boolean hasDispatchAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string dispatch_address = 1;</code>
       *
       * <pre>
       *The IPv4 address where the Dispatcher can be found.
       *e.g., 127.0.0.1, localhost, etc.
       * </pre>
       */
      public java.lang.String getDispatchAddress() {
        java.lang.Object ref = dispatchAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dispatchAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dispatch_address = 1;</code>
       *
       * <pre>
       *The IPv4 address where the Dispatcher can be found.
       *e.g., 127.0.0.1, localhost, etc.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDispatchAddressBytes() {
        java.lang.Object ref = dispatchAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dispatchAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dispatch_address = 1;</code>
       *
       * <pre>
       *The IPv4 address where the Dispatcher can be found.
       *e.g., 127.0.0.1, localhost, etc.
       * </pre>
       */
      public Builder setDispatchAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dispatchAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dispatch_address = 1;</code>
       *
       * <pre>
       *The IPv4 address where the Dispatcher can be found.
       *e.g., 127.0.0.1, localhost, etc.
       * </pre>
       */
      public Builder clearDispatchAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dispatchAddress_ = getDefaultInstance().getDispatchAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string dispatch_address = 1;</code>
       *
       * <pre>
       *The IPv4 address where the Dispatcher can be found.
       *e.g., 127.0.0.1, localhost, etc.
       * </pre>
       */
      public Builder setDispatchAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dispatchAddress_ = value;
        onChanged();
        return this;
      }

      // required int32 experiment_port = 2;
      private int experimentPort_ ;
      /**
       * <code>required int32 experiment_port = 2;</code>
       *
       * <pre>
       *The port that the dispatcher will be listening to.
       * </pre>
       */
      public boolean hasExperimentPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 experiment_port = 2;</code>
       *
       * <pre>
       *The port that the dispatcher will be listening to.
       * </pre>
       */
      public int getExperimentPort() {
        return experimentPort_;
      }
      /**
       * <code>required int32 experiment_port = 2;</code>
       *
       * <pre>
       *The port that the dispatcher will be listening to.
       * </pre>
       */
      public Builder setExperimentPort(int value) {
        bitField0_ |= 0x00000002;
        experimentPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 experiment_port = 2;</code>
       *
       * <pre>
       *The port that the dispatcher will be listening to.
       * </pre>
       */
      public Builder clearExperimentPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        experimentPort_ = 0;
        onChanged();
        return this;
      }

      // optional int32 reply_port = 3;
      private int replyPort_ ;
      /**
       * <code>optional int32 reply_port = 3;</code>
       *
       * <pre>
       *The secret to share in the communications (should be unique per contract)
       * </pre>
       */
      public boolean hasReplyPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 reply_port = 3;</code>
       *
       * <pre>
       *The secret to share in the communications (should be unique per contract)
       * </pre>
       */
      public int getReplyPort() {
        return replyPort_;
      }
      /**
       * <code>optional int32 reply_port = 3;</code>
       *
       * <pre>
       *The secret to share in the communications (should be unique per contract)
       * </pre>
       */
      public Builder setReplyPort(int value) {
        bitField0_ |= 0x00000004;
        replyPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 reply_port = 3;</code>
       *
       * <pre>
       *The secret to share in the communications (should be unique per contract)
       * </pre>
       */
      public Builder clearReplyPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        replyPort_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:search.Contract)
    }

    static {
      defaultInstance = new Contract(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:search.Contract)
  }

  public interface ExperimentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .search.Argument argument = 1;
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    java.util.List<core.messages.EmploySearcher.Argument> 
        getArgumentList();
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    core.messages.EmploySearcher.Argument getArgument(int index);
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    int getArgumentCount();
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    java.util.List<? extends core.messages.EmploySearcher.ArgumentOrBuilder> 
        getArgumentOrBuilderList();
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    core.messages.EmploySearcher.ArgumentOrBuilder getArgumentOrBuilder(
        int index);

    // optional bool terminal = 2 [default = false];
    /**
     * <code>optional bool terminal = 2 [default = false];</code>
     *
     * <pre>
     *True when there are no further experiments
     * </pre>
     */
    boolean hasTerminal();
    /**
     * <code>optional bool terminal = 2 [default = false];</code>
     *
     * <pre>
     *True when there are no further experiments
     * </pre>
     */
    boolean getTerminal();
  }
  /**
   * Protobuf type {@code search.Experiment}
   *
   * <pre>
   *Encapsulates the specific parameter settings of this experiment
   * </pre>
   */
  public static final class Experiment extends
      com.google.protobuf.GeneratedMessage
      implements ExperimentOrBuilder {
    // Use Experiment.newBuilder() to construct.
    private Experiment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Experiment(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Experiment defaultInstance;
    public static Experiment getDefaultInstance() {
      return defaultInstance;
    }

    public Experiment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Experiment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                argument_ = new java.util.ArrayList<core.messages.EmploySearcher.Argument>();
                mutable_bitField0_ |= 0x00000001;
              }
              argument_.add(input.readMessage(core.messages.EmploySearcher.Argument.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              terminal_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          argument_ = java.util.Collections.unmodifiableList(argument_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.messages.EmploySearcher.internal_static_search_Experiment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.messages.EmploySearcher.internal_static_search_Experiment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.messages.EmploySearcher.Experiment.class, core.messages.EmploySearcher.Experiment.Builder.class);
    }

    public static com.google.protobuf.Parser<Experiment> PARSER =
        new com.google.protobuf.AbstractParser<Experiment>() {
      public Experiment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Experiment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Experiment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .search.Argument argument = 1;
    public static final int ARGUMENT_FIELD_NUMBER = 1;
    private java.util.List<core.messages.EmploySearcher.Argument> argument_;
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    public java.util.List<core.messages.EmploySearcher.Argument> getArgumentList() {
      return argument_;
    }
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    public java.util.List<? extends core.messages.EmploySearcher.ArgumentOrBuilder> 
        getArgumentOrBuilderList() {
      return argument_;
    }
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    public int getArgumentCount() {
      return argument_.size();
    }
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    public core.messages.EmploySearcher.Argument getArgument(int index) {
      return argument_.get(index);
    }
    /**
     * <code>repeated .search.Argument argument = 1;</code>
     *
     * <pre>
     *The arguments to pass to the experiment program
     * </pre>
     */
    public core.messages.EmploySearcher.ArgumentOrBuilder getArgumentOrBuilder(
        int index) {
      return argument_.get(index);
    }

    // optional bool terminal = 2 [default = false];
    public static final int TERMINAL_FIELD_NUMBER = 2;
    private boolean terminal_;
    /**
     * <code>optional bool terminal = 2 [default = false];</code>
     *
     * <pre>
     *True when there are no further experiments
     * </pre>
     */
    public boolean hasTerminal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool terminal = 2 [default = false];</code>
     *
     * <pre>
     *True when there are no further experiments
     * </pre>
     */
    public boolean getTerminal() {
      return terminal_;
    }

    private void initFields() {
      argument_ = java.util.Collections.emptyList();
      terminal_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getArgumentCount(); i++) {
        if (!getArgument(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < argument_.size(); i++) {
        output.writeMessage(1, argument_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(2, terminal_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < argument_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, argument_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, terminal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static core.messages.EmploySearcher.Experiment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.EmploySearcher.Experiment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Experiment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.EmploySearcher.Experiment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Experiment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.EmploySearcher.Experiment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Experiment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static core.messages.EmploySearcher.Experiment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Experiment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.EmploySearcher.Experiment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(core.messages.EmploySearcher.Experiment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code search.Experiment}
     *
     * <pre>
     *Encapsulates the specific parameter settings of this experiment
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements core.messages.EmploySearcher.ExperimentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.messages.EmploySearcher.internal_static_search_Experiment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.messages.EmploySearcher.internal_static_search_Experiment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.messages.EmploySearcher.Experiment.class, core.messages.EmploySearcher.Experiment.Builder.class);
      }

      // Construct using core.messages.EmploySearcher.Experiment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getArgumentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (argumentBuilder_ == null) {
          argument_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          argumentBuilder_.clear();
        }
        terminal_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.messages.EmploySearcher.internal_static_search_Experiment_descriptor;
      }

      public core.messages.EmploySearcher.Experiment getDefaultInstanceForType() {
        return core.messages.EmploySearcher.Experiment.getDefaultInstance();
      }

      public core.messages.EmploySearcher.Experiment build() {
        core.messages.EmploySearcher.Experiment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public core.messages.EmploySearcher.Experiment buildPartial() {
        core.messages.EmploySearcher.Experiment result = new core.messages.EmploySearcher.Experiment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (argumentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            argument_ = java.util.Collections.unmodifiableList(argument_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.argument_ = argument_;
        } else {
          result.argument_ = argumentBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.terminal_ = terminal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.messages.EmploySearcher.Experiment) {
          return mergeFrom((core.messages.EmploySearcher.Experiment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.messages.EmploySearcher.Experiment other) {
        if (other == core.messages.EmploySearcher.Experiment.getDefaultInstance()) return this;
        if (argumentBuilder_ == null) {
          if (!other.argument_.isEmpty()) {
            if (argument_.isEmpty()) {
              argument_ = other.argument_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArgumentIsMutable();
              argument_.addAll(other.argument_);
            }
            onChanged();
          }
        } else {
          if (!other.argument_.isEmpty()) {
            if (argumentBuilder_.isEmpty()) {
              argumentBuilder_.dispose();
              argumentBuilder_ = null;
              argument_ = other.argument_;
              bitField0_ = (bitField0_ & ~0x00000001);
              argumentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArgumentFieldBuilder() : null;
            } else {
              argumentBuilder_.addAllMessages(other.argument_);
            }
          }
        }
        if (other.hasTerminal()) {
          setTerminal(other.getTerminal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getArgumentCount(); i++) {
          if (!getArgument(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        core.messages.EmploySearcher.Experiment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (core.messages.EmploySearcher.Experiment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .search.Argument argument = 1;
      private java.util.List<core.messages.EmploySearcher.Argument> argument_ =
        java.util.Collections.emptyList();
      private void ensureArgumentIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          argument_ = new java.util.ArrayList<core.messages.EmploySearcher.Argument>(argument_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          core.messages.EmploySearcher.Argument, core.messages.EmploySearcher.Argument.Builder, core.messages.EmploySearcher.ArgumentOrBuilder> argumentBuilder_;

      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public java.util.List<core.messages.EmploySearcher.Argument> getArgumentList() {
        if (argumentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(argument_);
        } else {
          return argumentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public int getArgumentCount() {
        if (argumentBuilder_ == null) {
          return argument_.size();
        } else {
          return argumentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public core.messages.EmploySearcher.Argument getArgument(int index) {
        if (argumentBuilder_ == null) {
          return argument_.get(index);
        } else {
          return argumentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public Builder setArgument(
          int index, core.messages.EmploySearcher.Argument value) {
        if (argumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentIsMutable();
          argument_.set(index, value);
          onChanged();
        } else {
          argumentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public Builder setArgument(
          int index, core.messages.EmploySearcher.Argument.Builder builderForValue) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.set(index, builderForValue.build());
          onChanged();
        } else {
          argumentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public Builder addArgument(core.messages.EmploySearcher.Argument value) {
        if (argumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentIsMutable();
          argument_.add(value);
          onChanged();
        } else {
          argumentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public Builder addArgument(
          int index, core.messages.EmploySearcher.Argument value) {
        if (argumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArgumentIsMutable();
          argument_.add(index, value);
          onChanged();
        } else {
          argumentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public Builder addArgument(
          core.messages.EmploySearcher.Argument.Builder builderForValue) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.add(builderForValue.build());
          onChanged();
        } else {
          argumentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public Builder addArgument(
          int index, core.messages.EmploySearcher.Argument.Builder builderForValue) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.add(index, builderForValue.build());
          onChanged();
        } else {
          argumentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public Builder addAllArgument(
          java.lang.Iterable<? extends core.messages.EmploySearcher.Argument> values) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          super.addAll(values, argument_);
          onChanged();
        } else {
          argumentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public Builder clearArgument() {
        if (argumentBuilder_ == null) {
          argument_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          argumentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public Builder removeArgument(int index) {
        if (argumentBuilder_ == null) {
          ensureArgumentIsMutable();
          argument_.remove(index);
          onChanged();
        } else {
          argumentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public core.messages.EmploySearcher.Argument.Builder getArgumentBuilder(
          int index) {
        return getArgumentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public core.messages.EmploySearcher.ArgumentOrBuilder getArgumentOrBuilder(
          int index) {
        if (argumentBuilder_ == null) {
          return argument_.get(index);  } else {
          return argumentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public java.util.List<? extends core.messages.EmploySearcher.ArgumentOrBuilder> 
           getArgumentOrBuilderList() {
        if (argumentBuilder_ != null) {
          return argumentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(argument_);
        }
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public core.messages.EmploySearcher.Argument.Builder addArgumentBuilder() {
        return getArgumentFieldBuilder().addBuilder(
            core.messages.EmploySearcher.Argument.getDefaultInstance());
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public core.messages.EmploySearcher.Argument.Builder addArgumentBuilder(
          int index) {
        return getArgumentFieldBuilder().addBuilder(
            index, core.messages.EmploySearcher.Argument.getDefaultInstance());
      }
      /**
       * <code>repeated .search.Argument argument = 1;</code>
       *
       * <pre>
       *The arguments to pass to the experiment program
       * </pre>
       */
      public java.util.List<core.messages.EmploySearcher.Argument.Builder> 
           getArgumentBuilderList() {
        return getArgumentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          core.messages.EmploySearcher.Argument, core.messages.EmploySearcher.Argument.Builder, core.messages.EmploySearcher.ArgumentOrBuilder> 
          getArgumentFieldBuilder() {
        if (argumentBuilder_ == null) {
          argumentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              core.messages.EmploySearcher.Argument, core.messages.EmploySearcher.Argument.Builder, core.messages.EmploySearcher.ArgumentOrBuilder>(
                  argument_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          argument_ = null;
        }
        return argumentBuilder_;
      }

      // optional bool terminal = 2 [default = false];
      private boolean terminal_ ;
      /**
       * <code>optional bool terminal = 2 [default = false];</code>
       *
       * <pre>
       *True when there are no further experiments
       * </pre>
       */
      public boolean hasTerminal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool terminal = 2 [default = false];</code>
       *
       * <pre>
       *True when there are no further experiments
       * </pre>
       */
      public boolean getTerminal() {
        return terminal_;
      }
      /**
       * <code>optional bool terminal = 2 [default = false];</code>
       *
       * <pre>
       *True when there are no further experiments
       * </pre>
       */
      public Builder setTerminal(boolean value) {
        bitField0_ |= 0x00000002;
        terminal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool terminal = 2 [default = false];</code>
       *
       * <pre>
       *True when there are no further experiments
       * </pre>
       */
      public Builder clearTerminal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        terminal_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:search.Experiment)
    }

    static {
      defaultInstance = new Experiment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:search.Experiment)
  }

  public interface ArgumentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string formal_name = 1;
    /**
     * <code>required string formal_name = 1;</code>
     */
    boolean hasFormalName();
    /**
     * <code>required string formal_name = 1;</code>
     */
    java.lang.String getFormalName();
    /**
     * <code>required string formal_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getFormalNameBytes();

    // required string value = 2;
    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code search.Argument}
   */
  public static final class Argument extends
      com.google.protobuf.GeneratedMessage
      implements ArgumentOrBuilder {
    // Use Argument.newBuilder() to construct.
    private Argument(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Argument(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Argument defaultInstance;
    public static Argument getDefaultInstance() {
      return defaultInstance;
    }

    public Argument getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Argument(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              formalName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.messages.EmploySearcher.internal_static_search_Argument_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.messages.EmploySearcher.internal_static_search_Argument_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.messages.EmploySearcher.Argument.class, core.messages.EmploySearcher.Argument.Builder.class);
    }

    public static com.google.protobuf.Parser<Argument> PARSER =
        new com.google.protobuf.AbstractParser<Argument>() {
      public Argument parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Argument(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Argument> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string formal_name = 1;
    public static final int FORMAL_NAME_FIELD_NUMBER = 1;
    private java.lang.Object formalName_;
    /**
     * <code>required string formal_name = 1;</code>
     */
    public boolean hasFormalName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string formal_name = 1;</code>
     */
    public java.lang.String getFormalName() {
      java.lang.Object ref = formalName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          formalName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string formal_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFormalNameBytes() {
      java.lang.Object ref = formalName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formalName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      formalName_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFormalName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFormalNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFormalNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static core.messages.EmploySearcher.Argument parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.EmploySearcher.Argument parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Argument parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.EmploySearcher.Argument parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Argument parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.EmploySearcher.Argument parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Argument parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static core.messages.EmploySearcher.Argument parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static core.messages.EmploySearcher.Argument parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.EmploySearcher.Argument parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(core.messages.EmploySearcher.Argument prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code search.Argument}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements core.messages.EmploySearcher.ArgumentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.messages.EmploySearcher.internal_static_search_Argument_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.messages.EmploySearcher.internal_static_search_Argument_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.messages.EmploySearcher.Argument.class, core.messages.EmploySearcher.Argument.Builder.class);
      }

      // Construct using core.messages.EmploySearcher.Argument.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        formalName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.messages.EmploySearcher.internal_static_search_Argument_descriptor;
      }

      public core.messages.EmploySearcher.Argument getDefaultInstanceForType() {
        return core.messages.EmploySearcher.Argument.getDefaultInstance();
      }

      public core.messages.EmploySearcher.Argument build() {
        core.messages.EmploySearcher.Argument result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public core.messages.EmploySearcher.Argument buildPartial() {
        core.messages.EmploySearcher.Argument result = new core.messages.EmploySearcher.Argument(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.formalName_ = formalName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.messages.EmploySearcher.Argument) {
          return mergeFrom((core.messages.EmploySearcher.Argument)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.messages.EmploySearcher.Argument other) {
        if (other == core.messages.EmploySearcher.Argument.getDefaultInstance()) return this;
        if (other.hasFormalName()) {
          bitField0_ |= 0x00000001;
          formalName_ = other.formalName_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFormalName()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        core.messages.EmploySearcher.Argument parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (core.messages.EmploySearcher.Argument) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string formal_name = 1;
      private java.lang.Object formalName_ = "";
      /**
       * <code>required string formal_name = 1;</code>
       */
      public boolean hasFormalName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string formal_name = 1;</code>
       */
      public java.lang.String getFormalName() {
        java.lang.Object ref = formalName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          formalName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string formal_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFormalNameBytes() {
        java.lang.Object ref = formalName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          formalName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string formal_name = 1;</code>
       */
      public Builder setFormalName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        formalName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string formal_name = 1;</code>
       */
      public Builder clearFormalName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        formalName_ = getDefaultInstance().getFormalName();
        onChanged();
        return this;
      }
      /**
       * <code>required string formal_name = 1;</code>
       */
      public Builder setFormalNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        formalName_ = value;
        onChanged();
        return this;
      }

      // required string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:search.Argument)
    }

    static {
      defaultInstance = new Argument(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:search.Argument)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_search_Contract_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_search_Contract_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_search_Experiment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_search_Experiment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_search_Argument_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_search_Argument_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contract.proto\022\006search\"Q\n\010Contract\022\030\n\020" +
      "dispatch_address\030\001 \002(\t\022\027\n\017experiment_por" +
      "t\030\002 \002(\005\022\022\n\nreply_port\030\003 \001(\005\"I\n\nExperimen" +
      "t\022\"\n\010argument\030\001 \003(\0132\020.search.Argument\022\027\n" +
      "\010terminal\030\002 \001(\010:\005false\".\n\010Argument\022\023\n\013fo" +
      "rmal_name\030\001 \002(\t\022\r\n\005value\030\002 \002(\tB\037\n\rcore.m" +
      "essagesB\016EmploySearcher"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_search_Contract_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_search_Contract_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_search_Contract_descriptor,
              new java.lang.String[] { "DispatchAddress", "ExperimentPort", "ReplyPort", });
          internal_static_search_Experiment_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_search_Experiment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_search_Experiment_descriptor,
              new java.lang.String[] { "Argument", "Terminal", });
          internal_static_search_Argument_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_search_Argument_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_search_Argument_descriptor,
              new java.lang.String[] { "FormalName", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
