// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: results.proto

package core.messages;

public final class ExperimentResults {
  private ExperimentResults() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResultMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .search.Result reported_value = 1;
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    java.util.List<core.messages.ExperimentResults.Result> 
        getReportedValueList();
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    core.messages.ExperimentResults.Result getReportedValue(int index);
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    int getReportedValueCount();
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    java.util.List<? extends core.messages.ExperimentResults.ResultOrBuilder> 
        getReportedValueOrBuilderList();
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    core.messages.ExperimentResults.ResultOrBuilder getReportedValueOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code search.ResultMessage}
   */
  public static final class ResultMessage extends
      com.google.protobuf.GeneratedMessage
      implements ResultMessageOrBuilder {
    // Use ResultMessage.newBuilder() to construct.
    private ResultMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResultMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResultMessage defaultInstance;
    public static ResultMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ResultMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResultMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                reportedValue_ = new java.util.ArrayList<core.messages.ExperimentResults.Result>();
                mutable_bitField0_ |= 0x00000001;
              }
              reportedValue_.add(input.readMessage(core.messages.ExperimentResults.Result.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          reportedValue_ = java.util.Collections.unmodifiableList(reportedValue_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.messages.ExperimentResults.internal_static_search_ResultMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.messages.ExperimentResults.internal_static_search_ResultMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.messages.ExperimentResults.ResultMessage.class, core.messages.ExperimentResults.ResultMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ResultMessage> PARSER =
        new com.google.protobuf.AbstractParser<ResultMessage>() {
      public ResultMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResultMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResultMessage> getParserForType() {
      return PARSER;
    }

    // repeated .search.Result reported_value = 1;
    public static final int REPORTED_VALUE_FIELD_NUMBER = 1;
    private java.util.List<core.messages.ExperimentResults.Result> reportedValue_;
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    public java.util.List<core.messages.ExperimentResults.Result> getReportedValueList() {
      return reportedValue_;
    }
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    public java.util.List<? extends core.messages.ExperimentResults.ResultOrBuilder> 
        getReportedValueOrBuilderList() {
      return reportedValue_;
    }
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    public int getReportedValueCount() {
      return reportedValue_.size();
    }
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    public core.messages.ExperimentResults.Result getReportedValue(int index) {
      return reportedValue_.get(index);
    }
    /**
     * <code>repeated .search.Result reported_value = 1;</code>
     */
    public core.messages.ExperimentResults.ResultOrBuilder getReportedValueOrBuilder(
        int index) {
      return reportedValue_.get(index);
    }

    private void initFields() {
      reportedValue_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getReportedValueCount(); i++) {
        if (!getReportedValue(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < reportedValue_.size(); i++) {
        output.writeMessage(1, reportedValue_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < reportedValue_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reportedValue_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static core.messages.ExperimentResults.ResultMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.ExperimentResults.ResultMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.ExperimentResults.ResultMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.ExperimentResults.ResultMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.ExperimentResults.ResultMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.ExperimentResults.ResultMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static core.messages.ExperimentResults.ResultMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static core.messages.ExperimentResults.ResultMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static core.messages.ExperimentResults.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.ExperimentResults.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(core.messages.ExperimentResults.ResultMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code search.ResultMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements core.messages.ExperimentResults.ResultMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.messages.ExperimentResults.internal_static_search_ResultMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.messages.ExperimentResults.internal_static_search_ResultMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.messages.ExperimentResults.ResultMessage.class, core.messages.ExperimentResults.ResultMessage.Builder.class);
      }

      // Construct using core.messages.ExperimentResults.ResultMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReportedValueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (reportedValueBuilder_ == null) {
          reportedValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          reportedValueBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.messages.ExperimentResults.internal_static_search_ResultMessage_descriptor;
      }

      public core.messages.ExperimentResults.ResultMessage getDefaultInstanceForType() {
        return core.messages.ExperimentResults.ResultMessage.getDefaultInstance();
      }

      public core.messages.ExperimentResults.ResultMessage build() {
        core.messages.ExperimentResults.ResultMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public core.messages.ExperimentResults.ResultMessage buildPartial() {
        core.messages.ExperimentResults.ResultMessage result = new core.messages.ExperimentResults.ResultMessage(this);
        int from_bitField0_ = bitField0_;
        if (reportedValueBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            reportedValue_ = java.util.Collections.unmodifiableList(reportedValue_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.reportedValue_ = reportedValue_;
        } else {
          result.reportedValue_ = reportedValueBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.messages.ExperimentResults.ResultMessage) {
          return mergeFrom((core.messages.ExperimentResults.ResultMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.messages.ExperimentResults.ResultMessage other) {
        if (other == core.messages.ExperimentResults.ResultMessage.getDefaultInstance()) return this;
        if (reportedValueBuilder_ == null) {
          if (!other.reportedValue_.isEmpty()) {
            if (reportedValue_.isEmpty()) {
              reportedValue_ = other.reportedValue_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureReportedValueIsMutable();
              reportedValue_.addAll(other.reportedValue_);
            }
            onChanged();
          }
        } else {
          if (!other.reportedValue_.isEmpty()) {
            if (reportedValueBuilder_.isEmpty()) {
              reportedValueBuilder_.dispose();
              reportedValueBuilder_ = null;
              reportedValue_ = other.reportedValue_;
              bitField0_ = (bitField0_ & ~0x00000001);
              reportedValueBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getReportedValueFieldBuilder() : null;
            } else {
              reportedValueBuilder_.addAllMessages(other.reportedValue_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getReportedValueCount(); i++) {
          if (!getReportedValue(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        core.messages.ExperimentResults.ResultMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (core.messages.ExperimentResults.ResultMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .search.Result reported_value = 1;
      private java.util.List<core.messages.ExperimentResults.Result> reportedValue_ =
        java.util.Collections.emptyList();
      private void ensureReportedValueIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          reportedValue_ = new java.util.ArrayList<core.messages.ExperimentResults.Result>(reportedValue_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          core.messages.ExperimentResults.Result, core.messages.ExperimentResults.Result.Builder, core.messages.ExperimentResults.ResultOrBuilder> reportedValueBuilder_;

      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public java.util.List<core.messages.ExperimentResults.Result> getReportedValueList() {
        if (reportedValueBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reportedValue_);
        } else {
          return reportedValueBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public int getReportedValueCount() {
        if (reportedValueBuilder_ == null) {
          return reportedValue_.size();
        } else {
          return reportedValueBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public core.messages.ExperimentResults.Result getReportedValue(int index) {
        if (reportedValueBuilder_ == null) {
          return reportedValue_.get(index);
        } else {
          return reportedValueBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public Builder setReportedValue(
          int index, core.messages.ExperimentResults.Result value) {
        if (reportedValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReportedValueIsMutable();
          reportedValue_.set(index, value);
          onChanged();
        } else {
          reportedValueBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public Builder setReportedValue(
          int index, core.messages.ExperimentResults.Result.Builder builderForValue) {
        if (reportedValueBuilder_ == null) {
          ensureReportedValueIsMutable();
          reportedValue_.set(index, builderForValue.build());
          onChanged();
        } else {
          reportedValueBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public Builder addReportedValue(core.messages.ExperimentResults.Result value) {
        if (reportedValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReportedValueIsMutable();
          reportedValue_.add(value);
          onChanged();
        } else {
          reportedValueBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public Builder addReportedValue(
          int index, core.messages.ExperimentResults.Result value) {
        if (reportedValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReportedValueIsMutable();
          reportedValue_.add(index, value);
          onChanged();
        } else {
          reportedValueBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public Builder addReportedValue(
          core.messages.ExperimentResults.Result.Builder builderForValue) {
        if (reportedValueBuilder_ == null) {
          ensureReportedValueIsMutable();
          reportedValue_.add(builderForValue.build());
          onChanged();
        } else {
          reportedValueBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public Builder addReportedValue(
          int index, core.messages.ExperimentResults.Result.Builder builderForValue) {
        if (reportedValueBuilder_ == null) {
          ensureReportedValueIsMutable();
          reportedValue_.add(index, builderForValue.build());
          onChanged();
        } else {
          reportedValueBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public Builder addAllReportedValue(
          java.lang.Iterable<? extends core.messages.ExperimentResults.Result> values) {
        if (reportedValueBuilder_ == null) {
          ensureReportedValueIsMutable();
          super.addAll(values, reportedValue_);
          onChanged();
        } else {
          reportedValueBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public Builder clearReportedValue() {
        if (reportedValueBuilder_ == null) {
          reportedValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          reportedValueBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public Builder removeReportedValue(int index) {
        if (reportedValueBuilder_ == null) {
          ensureReportedValueIsMutable();
          reportedValue_.remove(index);
          onChanged();
        } else {
          reportedValueBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public core.messages.ExperimentResults.Result.Builder getReportedValueBuilder(
          int index) {
        return getReportedValueFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public core.messages.ExperimentResults.ResultOrBuilder getReportedValueOrBuilder(
          int index) {
        if (reportedValueBuilder_ == null) {
          return reportedValue_.get(index);  } else {
          return reportedValueBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public java.util.List<? extends core.messages.ExperimentResults.ResultOrBuilder> 
           getReportedValueOrBuilderList() {
        if (reportedValueBuilder_ != null) {
          return reportedValueBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reportedValue_);
        }
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public core.messages.ExperimentResults.Result.Builder addReportedValueBuilder() {
        return getReportedValueFieldBuilder().addBuilder(
            core.messages.ExperimentResults.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public core.messages.ExperimentResults.Result.Builder addReportedValueBuilder(
          int index) {
        return getReportedValueFieldBuilder().addBuilder(
            index, core.messages.ExperimentResults.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .search.Result reported_value = 1;</code>
       */
      public java.util.List<core.messages.ExperimentResults.Result.Builder> 
           getReportedValueBuilderList() {
        return getReportedValueFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          core.messages.ExperimentResults.Result, core.messages.ExperimentResults.Result.Builder, core.messages.ExperimentResults.ResultOrBuilder> 
          getReportedValueFieldBuilder() {
        if (reportedValueBuilder_ == null) {
          reportedValueBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              core.messages.ExperimentResults.Result, core.messages.ExperimentResults.Result.Builder, core.messages.ExperimentResults.ResultOrBuilder>(
                  reportedValue_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          reportedValue_ = null;
        }
        return reportedValueBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:search.ResultMessage)
    }

    static {
      defaultInstance = new ResultMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:search.ResultMessage)
  }

  public interface ResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *The name of the result
     * </pre>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *The name of the result
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *The name of the result
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string value = 2;
    /**
     * <code>required string value = 2;</code>
     *
     * <pre>
     *The value of the reported result, will be parsed according to the given type
     * </pre>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     *
     * <pre>
     *The value of the reported result, will be parsed according to the given type
     * </pre>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     *
     * <pre>
     *The value of the reported result, will be parsed according to the given type
     * </pre>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    // optional .search.Result.Type type = 3 [default = string];
    /**
     * <code>optional .search.Result.Type type = 3 [default = string];</code>
     *
     * <pre>
     *The data type of the result (for storage in DB), string will be attempted to be parsed as numeric
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional .search.Result.Type type = 3 [default = string];</code>
     *
     * <pre>
     *The data type of the result (for storage in DB), string will be attempted to be parsed as numeric
     * </pre>
     */
    core.messages.ExperimentResults.Result.Type getType();
  }
  /**
   * Protobuf type {@code search.Result}
   */
  public static final class Result extends
      com.google.protobuf.GeneratedMessage
      implements ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Result(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Result defaultInstance;
    public static Result getDefaultInstance() {
      return defaultInstance;
    }

    public Result getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              core.messages.ExperimentResults.Result.Type value = core.messages.ExperimentResults.Result.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.messages.ExperimentResults.internal_static_search_Result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.messages.ExperimentResults.internal_static_search_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.messages.ExperimentResults.Result.class, core.messages.ExperimentResults.Result.Builder.class);
    }

    public static com.google.protobuf.Parser<Result> PARSER =
        new com.google.protobuf.AbstractParser<Result>() {
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code search.Result.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>int32 = 0;</code>
       */
      int32(0, 0),
      /**
       * <code>float32 = 1;</code>
       */
      float32(1, 1),
      /**
       * <code>float64 = 2;</code>
       */
      float64(2, 2),
      /**
       * <code>string = 3;</code>
       */
      string(3, 3),
      /**
       * <code>bool = 4;</code>
       */
      bool(4, 4),
      /**
       * <code>int64 = 5;</code>
       */
      int64(5, 5),
      ;

      /**
       * <code>int32 = 0;</code>
       */
      public static final int int32_VALUE = 0;
      /**
       * <code>float32 = 1;</code>
       */
      public static final int float32_VALUE = 1;
      /**
       * <code>float64 = 2;</code>
       */
      public static final int float64_VALUE = 2;
      /**
       * <code>string = 3;</code>
       */
      public static final int string_VALUE = 3;
      /**
       * <code>bool = 4;</code>
       */
      public static final int bool_VALUE = 4;
      /**
       * <code>int64 = 5;</code>
       */
      public static final int int64_VALUE = 5;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return int32;
          case 1: return float32;
          case 2: return float64;
          case 3: return string;
          case 4: return bool;
          case 5: return int64;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return core.messages.ExperimentResults.Result.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:search.Result.Type)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *The name of the result
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *The name of the result
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     *The name of the result
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     *
     * <pre>
     *The value of the reported result, will be parsed according to the given type
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     *
     * <pre>
     *The value of the reported result, will be parsed according to the given type
     * </pre>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     *
     * <pre>
     *The value of the reported result, will be parsed according to the given type
     * </pre>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .search.Result.Type type = 3 [default = string];
    public static final int TYPE_FIELD_NUMBER = 3;
    private core.messages.ExperimentResults.Result.Type type_;
    /**
     * <code>optional .search.Result.Type type = 3 [default = string];</code>
     *
     * <pre>
     *The data type of the result (for storage in DB), string will be attempted to be parsed as numeric
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .search.Result.Type type = 3 [default = string];</code>
     *
     * <pre>
     *The data type of the result (for storage in DB), string will be attempted to be parsed as numeric
     * </pre>
     */
    public core.messages.ExperimentResults.Result.Type getType() {
      return type_;
    }

    private void initFields() {
      name_ = "";
      value_ = "";
      type_ = core.messages.ExperimentResults.Result.Type.string;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static core.messages.ExperimentResults.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.ExperimentResults.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.ExperimentResults.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.messages.ExperimentResults.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.messages.ExperimentResults.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.ExperimentResults.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static core.messages.ExperimentResults.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static core.messages.ExperimentResults.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static core.messages.ExperimentResults.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static core.messages.ExperimentResults.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(core.messages.ExperimentResults.Result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code search.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements core.messages.ExperimentResults.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.messages.ExperimentResults.internal_static_search_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.messages.ExperimentResults.internal_static_search_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.messages.ExperimentResults.Result.class, core.messages.ExperimentResults.Result.Builder.class);
      }

      // Construct using core.messages.ExperimentResults.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = core.messages.ExperimentResults.Result.Type.string;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.messages.ExperimentResults.internal_static_search_Result_descriptor;
      }

      public core.messages.ExperimentResults.Result getDefaultInstanceForType() {
        return core.messages.ExperimentResults.Result.getDefaultInstance();
      }

      public core.messages.ExperimentResults.Result build() {
        core.messages.ExperimentResults.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public core.messages.ExperimentResults.Result buildPartial() {
        core.messages.ExperimentResults.Result result = new core.messages.ExperimentResults.Result(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.messages.ExperimentResults.Result) {
          return mergeFrom((core.messages.ExperimentResults.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.messages.ExperimentResults.Result other) {
        if (other == core.messages.ExperimentResults.Result.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        core.messages.ExperimentResults.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (core.messages.ExperimentResults.Result) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *The name of the result
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *The name of the result
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *The name of the result
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *The name of the result
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *The name of the result
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       *The name of the result
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       *The value of the reported result, will be parsed according to the given type
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       *The value of the reported result, will be parsed according to the given type
       * </pre>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       *The value of the reported result, will be parsed according to the given type
       * </pre>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       *The value of the reported result, will be parsed according to the given type
       * </pre>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       *The value of the reported result, will be parsed according to the given type
       * </pre>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       *
       * <pre>
       *The value of the reported result, will be parsed according to the given type
       * </pre>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // optional .search.Result.Type type = 3 [default = string];
      private core.messages.ExperimentResults.Result.Type type_ = core.messages.ExperimentResults.Result.Type.string;
      /**
       * <code>optional .search.Result.Type type = 3 [default = string];</code>
       *
       * <pre>
       *The data type of the result (for storage in DB), string will be attempted to be parsed as numeric
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .search.Result.Type type = 3 [default = string];</code>
       *
       * <pre>
       *The data type of the result (for storage in DB), string will be attempted to be parsed as numeric
       * </pre>
       */
      public core.messages.ExperimentResults.Result.Type getType() {
        return type_;
      }
      /**
       * <code>optional .search.Result.Type type = 3 [default = string];</code>
       *
       * <pre>
       *The data type of the result (for storage in DB), string will be attempted to be parsed as numeric
       * </pre>
       */
      public Builder setType(core.messages.ExperimentResults.Result.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .search.Result.Type type = 3 [default = string];</code>
       *
       * <pre>
       *The data type of the result (for storage in DB), string will be attempted to be parsed as numeric
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = core.messages.ExperimentResults.Result.Type.string;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:search.Result)
    }

    static {
      defaultInstance = new Result(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:search.Result)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_search_ResultMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_search_ResultMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_search_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_search_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rresults.proto\022\006search\"7\n\rResultMessage" +
      "\022&\n\016reported_value\030\001 \003(\0132\016.search.Result" +
      "\"\236\001\n\006Result\022\014\n\004name\030\001 \002(\t\022\r\n\005value\030\002 \002(\t" +
      "\022)\n\004type\030\003 \001(\0162\023.search.Result.Type:\006str" +
      "ing\"L\n\004Type\022\t\n\005int32\020\000\022\013\n\007float32\020\001\022\013\n\007f" +
      "loat64\020\002\022\n\n\006string\020\003\022\010\n\004bool\020\004\022\t\n\005int64\020" +
      "\005B\"\n\rcore.messagesB\021ExperimentResults"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_search_ResultMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_search_ResultMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_search_ResultMessage_descriptor,
              new java.lang.String[] { "ReportedValue", });
          internal_static_search_Result_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_search_Result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_search_Result_descriptor,
              new java.lang.String[] { "Name", "Value", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
